### ISSUE TITLE
A lock file already exists in the repository, which blocks this operation from completing.

### ISSUE THREAD

**Issue by Ajay-Dhangar** [Ajay-Dhangar/Web-Technology#1]
I've created a new repository with GitHub desktop( i couldn't add the local repository for some reason) in my small react app. When I want to commit I get the error message: A lock file already exists in the repository, which blocks this operation from completing.

I've deleted the package-lock.json file but it doesn't help. react build is not running. no idea what causes this. thanks for your help

**Version**
GitHub Desktop:1.3.4
Operating system: Windows 11Home Premium 64-Bit
Steps to Reproduce
Add Local Repository. Choose Repository. Get redirected to create a new repository.
create a new repository in the project folder
try to commit and get the error message: A lock file already exists in the repository, which blocks this operation from completing.
Expected Behavior
Commit goes trough
[EULA.pdf](https://github.com/Ajay-Dhangar/Web-Technology/files/9089023/EULA.pdf)

![Step-1](https://user-images.githubusercontent.com/99037494/178406059-fea0307a-4f50-4e21-baa8-4eb6feb1429d.png)

**Actual Behavior**
Get Error Message: A lock file already exists in the repository, which blocks this operation from completing.

**Comment by Ajay-Dhangar** [comment]
**### Solutions:** 

Read this article  👉 https://ajaydhangar49.medium.com/a-lock-file-already-exists-in-the-repository-which-blocks-this-operation-from-completing-ebe0b504dbfa 


![Step-1](https://user-images.githubusercontent.com/99037494/178405619-7e27593d-754a-4e23-90e9-9df0794d8488.png)
![Step-2](https://user-images.githubusercontent.com/99037494/178405639-407bf064-d2ed-4a9b-bc86-f07b05444397.png)
![Step-3](https://user-images.githubusercontent.com/99037494/178405644-f279eda9-5f4f-4e17-8019-63790e51dec9.png)
![Step-4](https://user-images.githubusercontent.com/99037494/178405828-eada1171-7ce4-4364-8a3c-997e40264c03.png)
![Step-5](https://user-images.githubusercontent.com/99037494/178405850-3f8f164c-a987-41c0-b1f5-a4c865344f4a.png)
![Step-6](https://user-images.githubusercontent.com/99037494/178405881-52c198ac-a472-41fb-8331-2b6b1d042522.png)
![Step-7](https://user-images.githubusercontent.com/99037494/178405887-92c9fa2d-d694-4401-8f18-3b9ed9fdc9a0.png)
![Step-8](https://user-images.githubusercontent.com/99037494/178405904-4deea3a0-8efa-4885-af9c-40fcd4bceab7.png)
![Step-9](https://user-images.githubusercontent.com/99037494/178405914-805e4cb2-834e-4cf0-9e48-ed62169c5bc0.png)

**Comment by shivay2001** [comment]
Great Sir, Thanks for sharing the solution to this problem.
